version: "3"
services: 
  app:
    container_name: first_project
    restart: always
    build: .
    ports: 
      - "3001:3001"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27017"